services:
    user-service:
        build:
            target: development
        env_file:
            - ./services/user-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=user_service_dev
            - RABBITMQ_URL=amqp://rabbitmq:5672

    notification-service:
        build:
            target: development
        env_file:
            - ./services/notification-service/.env
        environment:
            - RABBITMQ_URL=amqp://rabbitmq:5672

    upload-image-service:
        build:
            target: development
        env_file:
            - ./services/upload-image-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=upload_image_dev
            - RABBITMQ_URL=amqp://rabbitmq:5672
            - HOST=upload-image-service
            - FIXED_HASH = hashFixedValue

    process-image-service:
        build:
            target: development
        env_file:
            - ./services/process-image-service/.env
        environment:
            - RABBITMQ_URL=amqp://rabbitmq:5672
