version: "3.9"
services:
    user-service:
        build:
            context: services/user-service
            target: development
        env_file:
            - services/user-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=image_processing_development
            - RABBITMQ_URL=amqp://rabbitmq:5672
        volumes:
            - ./services/user-service/src:/app/user-service/src:ro

        depends_on:
            - postgres
            - rabbitmq

    notification-service:
        build:
            context: services/notification-service
            target: development
        env_file:
            - services/notification-service/.env
        volumes:
            - ./services/notification-service/src:/app/notification-service/src:ro
        environment:
            - RABBITMQ_URL=amqp://rabbitmq:5672
        depends_on:
            - rabbitmq

    postgres:
        image: postgres
        container_name: postgres-container
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: image_processing_development
