version: "3.9"
services:
    user-service:
        build:
            context: services/user-service
            target: test
        env_file:
            - services/user-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=image_processing_test

    notification-service:
        build:
            context: services/notification-service
            target: test

    upload-image-service:
        build:
            target: test
        env_file:
            - ./services/upload-image-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=upload_image_test
            - RABBITMQ_URL=amqp://rabbitmq:5672
