version: "3"
services:
    user-service:
        build:
            context: services/user-service
            target: production
    notification-service:
        build:
            context: services/notification-service
            target: production
