services:
    user-service:
        build:
            context: services/user-service
        container_name: user-service
        image: user-service
        volumes:
            - ./services/user-service/src:/app/user-service/src:ro
        ports:
            - "6000:6000"
        depends_on:
            - rabbitmq

    notification-service:
        build:
            context: services/notification-service
        container_name: notification-service
        image: notification-service
        volumes:
            - ./services/notification-service/src:/app/notification-service/src:ro
        ports:
            - "5000:5000"
        depends_on:
            - rabbitmq

    upload-image-service:
        build:
            context: ./services/upload-image-service
        container_name: upload-image-service
        image: upload-image-service
        volumes:
            - ./services/upload-image-service/src:/app/upload-image-service/src:ro
        ports:
            - 4000:4000

    process-image-service:
        build:
            context: ./services/process-image-service
        container_name: process-image-services
        image: process-image-service
        volumes:
            - ./services/process-image-service/src:/app/process-image-service/src:ro
        ports:
            - 9000:9000

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    rabbitmq_data:
