version: "3"
services:
    user-service:
        build:
            context: services/user-service
        container_name: user-service
        image: user-service:latest
        volumes:
            - ./services/user-service/src:/app/user-service/src:ro
        ports:
            - "3000:3000"

