version: "3.9"
services:
    user-service:
        build:
            context: services/user-service
            target: test
        env_file:
            - services/user-service/.env
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=postgres
            - DATABASE_NAME=image_processing_test
        depends_on:
            - postgres
    
    
    notification-service:
        build:
            context: services/notification-service
            target: test
        depends_on:
            - rabbitmq

    postgres:
        image: postgres
        container_name: postgres-container
        ports:
            - "5432:5432"
        volumes:
            - pgdata-test:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: image_processing_test
volumes:
    pgdata-test: