services:
    user-service:
        build:
            context: services/user-service
        container_name: user-service
        image: user-service
        ports:
            - "6000:6000"
        depends_on:
            - rabbitmq

    notification-service:
        build:
            context: services/notification-service
        container_name: notification-service
        image: notification-service
        ports:
            - "5000:5000"
        depends_on:
            - rabbitmq

    upload-image-service:
        build:
            context: ./services/upload-image-service
        container_name: upload-image-service
        image: upload-image-service
        ports:
            - 4000:4000

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    rabbitmq_data:
